version: "3.7"

services:

  db:
    image: postgres:14-alpine
    container_name: gitea-db
    restart: unless-stopped
    networks:
      - gitea
    environment:
      - POSTGRES_DB=${GITEA_DB_NAME:-giteadb}
      - POSTGRES_USER=${GITEA_DB_USER:-gitea}
      - POSTGRES_PASSWORD=${GITEA_DB_PASS:-password}
    volumes:
      - ${GITEA_PATH:-gitea-db}:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U ${GITEA_DB_USER:-gitea} -d ${GITEA_DB_NAME:-giteadb}
      interval: 10s
      timeout: 2s
      retries: 10

  gitea:
    image: gitea/gitea:latest
    container_name: gitea
    restart: unless-stopped
    networks:
      - gitea
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ${GITEA_PATH:-gitea-data}:/data
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - SSH_LISTEN_PORT=22
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=db:5432
      - GITEA__database__NAME=${GITEA_DB_NAME:-giteadb}
      - GITEA__database__USER=${GITEA_DB_USER:-gitea}
      - GITEA__database__PASSWD=${GITEA_DB_PASS:-password}

volumes:
  gitea-db:
    name: gitea-db
  gitea-data:
    name: gitea-data

networks:
  gitea:
    name: gitea
